#include "FPS.h"

/*
Library C++ FPS - Control frames per second.
Copyright (C) 1013 Eduardo Moura Sales Martins
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
email: edimartin@gmail.com.br

AV: Walmor M. de Souza 392 Casa
Gravatai RS Brazil 94065100
*/

#ifdef WIN32
    //Windows 32
#elif WIN64
    //Windows 64
#elif __linux__
    //Linux
#elif __APPLE__
    //MacOS
#endif

namespace edk {
namespace watch {




FPS::FPS()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-2df785f1:13aeab90460:-8000:000000000000266D begin
{
    //clean the FPS
    this->setFPS(0u);
    this->start();
}
// section 127-0-1-1-2df785f1:13aeab90460:-8000:000000000000266D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

FPS::FPS(uint32 fps)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB0D begin
{
    //set the new FPS
    this->setFPS(fps);
    this->start();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB0D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void FPS::start()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB18 begin
{
    //clear the clock
    clock.start();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB18 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void FPS::setFPS(uint32 fps)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB1A begin
{
    //test if the FPS is not zero
    if(fps){
        //then set the fps
        this->frames = fps;
    }
    else{
        //else set the fps with one
        this->frames=0u;
    }
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB1A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool FPS::waitForFPS()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB1D begin
{
    bool ret=false;
    if(this->frames){
        //calculate the remainder microsecons to get one second
        register edk::int32 wait=(edk::uint32)(((1.0f/(float)frames))*edk::watch::second) - clock.getMicroseconds();
        if(wait>0){
            //If the distance bigger than zero. He need wait.
        //Windows sleep millisecons
        #ifdef _WIN32 || _WIN64
            clock.sleepProcessMiliseconds(wait*0.001);
        #else
            clock.sleepProcessMicroseconds(wait);
        #endif

            ret=true;
        }

        //after this he can start a new time count
        start();
    }
    return ret;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AB1D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace edk::ptr */
} /* End of namespace edk */
