#include "Window.h"

/*
Library C++ Window - Manipulate a window in Edk Game Engine
Copyright (C) 2013 Eduardo Moura Sales Martins
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
email: edimartin@gmail.com.br

AV: Walmor M. de Souza 392 Casa
Gravatai RS Brazil 94065100
*/

#ifdef printMessages
#warning "            Inside Window.cpp"
#endif

namespace edk {

//PRIVATE
//Atualiza o tamanho da view
void edk::Window::updateViewSize(){
    //seta o tamanho da view
    this->viewWindow.frame=edk::rectf32(0.f,0.f,(edk::float32)this->getScreenSize().width,(edk::float32)this->getScreenSize().height);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::cleanEvents(){
    //
    this->events.clean();
}


Window::Window()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA24 begin
{
    //ctor
    //por padrao a window e o mouse sao renderizados
    this->renderMouse = true;
    this->renderWindow = true;
    this->activeRender = false;
    this->windowFocus = true;
    this->mouseInside=false;
    this->cleanEvents();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA24 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Window::~Window(){
    //clean the events
    this->cleanEvents();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA26 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::createWindow(uint32 width, uint32 height/*, uint32 bitsPerPixel*/, char8 *name, typeID design, uint32 depth, uint32 stencil, uint32 antialiasing)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA28 begin
{
    uint32 bitsPerPixel=0u;
    //antes fecha a janela anterior
    if(this->isOpened()){
        //fecha a janela
        this->closeWindow();
    }

    //testa se a string e valida
    if(name){

        //calcula o estilo da janela
        edk::uint32 style = 0u;

        if(design & EDK_WINDOW_NOBAR){
            //
            style = style | sf::Style::None;//Desenha a janela sem uma barra de titulo
        }
        if(design & EDK_WINDOW_BUTTONS){
            //
            style = style | sf::Style::Close;//Desenha a janela com o botao de close e o minimize
        }
        if(design & EDK_WINDOW_BAR){
            //
            style = style | sf::Style::Titlebar;//Desenha a janela com a barra de titulo
        }
        if(design & EDK_WINDOW_RESIZE){
            //
            style = style | sf::Style::Resize;//Deixa a janela ser redimensionada
        }
        if(design & EDK_WINDOW_FULLSCREEN){
            //
            style = style | sf::Style::Fullscreen;//Desenha a janela em FULLSCREEN
        }

        /*
        switch(design){
            //
            case EDK_WINDOW_NOBAR:
                //
                style = style | sf::Style::None;//Desenha a janela sem uma barra de titulo
                break;
            case EDK_WINDOW_BUTTONS:
                //
                style = style | sf::Style::Close;//Desenha a janela com o botao de close e o minimize
                break;
            case EDK_WINDOW_BAR:
                //
                style = style | sf::Style::Titlebar;//Desenha a janela com a barra de titulo
                break;
            case EDK_WINDOW_RESIZE:
                //
                style = style | sf::Style::Resize;//Deixa a janela ser redimensionada
                break;
            case EDK_WINDOW_FULLSCREEN:
                //
                style = sf::Style::Fullscreen;//Desenha a janela em FULLSCREEN
                break;
            }
        */



        /*
        // Display the list of all the video modes available for fullscreen
        std::vector<sf::VideoMode> modes = sf::VideoMode::getFullscreenModes();
        for (std::size_t i = 0; i < modes.size(); ++i)
        {
            sf::VideoMode mode = modes[i];
            std::cout << "Mode #" << i << ": "
                      << mode.width << "x" << mode.height << " - "
                      << mode.bitsPerPixel << " bpp" << std::endl;
        }
        // Create a window with the same pixel depth as the desktop
        sf::VideoMode desktop = sf::VideoMode::getDesktopMode();
        window.create(sf::VideoMode(1024, 768, desktop.bitsPerPixel), "SFML window");
*/

        sf::VideoMode desktop = sf::VideoMode::getDesktopMode();
        bitsPerPixel = desktop.bitsPerPixel;
        //Agora ele pode criar a janela
        //this->window.Create(sf::VideoMode(width, height, bitsPerPixel),(const char*)name,style,sf::WindowSettings(depth,stencil,antialiasing));//1.6
        this->window.create(sf::VideoMode(width, height, bitsPerPixel),(const char*)name,style,sf::ContextSettings(depth,stencil,antialiasing));//2.0

        //Testa se a janela foi aberta
        if(this->isOpened()){
            //set the size of the window
            this->setWindowSize(width,height);
            //Seta a renderizacao da window
            //this->window.Show(this->renderWindow);//1.6
            this->window.setVisible(this->renderWindow);//2.0
            //Seta a renderizacao do mouse
            //this->window.ShowMouseCursor(this->renderMouse);//1.6
            this->window.setMouseCursorVisible(this->renderMouse);//2.0
            //Seta a keyRepeat como true
            //this->window.EnableKeyRepeat(true);//1.6
            this->window.setKeyRepeatEnabled(true);//2.0
            //Seta o tamanho da window
            this->setWindowSize(width,height);

            //set the blend with alpha channel
            edk::GU::guEnable(GU_BLEND);
            edk::GU::guBlendFunc(GU_SRC_ALPHA,GU_ONE_MINUS_SRC_ALPHA);

            //retorna true
            return true;
        }
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA28 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::createWindow(uint32 width, uint32 height/*, uint32 bitsPerPixel*/, const char *name, typeID design, uint32 depth, uint32 stencil, uint32 antialiasing)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--13345efa:13aea2ffc7e:-8000:000000000000182D begin
{
    //
    return this->createWindow(width,height/*,bitsPerPixel*/,
                              (edk::char8*) name,
                              design,
                              depth,stencil,antialiasing
                              );
}
// section 127-0-1-1--13345efa:13aea2ffc7e:-8000:000000000000182D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::createWindow(uint32  width, uint32  height/*, uint32  bitsPerPixel*/, char8 *name, typeID design)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA41 begin
{
    //
    return this->createWindow(width,height/*,bitsPerPixel*/,
                              name,
                              design,
                              24u,8u,0u
                              );
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA41 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::createWindow(uint32  width, uint32  height/*, uint32  bitsPerPixel*/, const char *name, typeID  design)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--2410b439:13aea535044:-8000:0000000000001837 begin
{
    return this->createWindow(width, height/*, bitsPerPixel*/,
                              (char8 *)name,
                              design,
                              24u,8u,0u
                              );
}
// section 127-0-1-1--2410b439:13aea535044:-8000:0000000000001837 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::isOpened()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA53 begin
{
    //antes fecha a janela anterior
    //if(this->window.IsOpened()){1.6
    if(this->window.isOpen()){//2.0
        //fecha a janela
        return true;
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::isShowing()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA55 begin
{
    //retorna se a janela esta sendo mostrada
    return this->renderWindow;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA55 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::haveFocus()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA57 begin
{
    //
    return this->windowFocus;
    //return this->events.focus;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA57 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::closeWindow()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA59 begin
{
    edk::GU::guDisable(GU_BLEND);
    //
    //if(this->window.IsOpened()){//1.6
    if(this->window.isOpen()){//2.0
        //
        //this->window.Close();//1.6
        this->window.close();//2.0
    }
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA59 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::clean()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA5B begin
{
    //
    if(this->isOpened()){
        //Entao ele pode limpar a janela
        //this->window.Clear(sf::Color((edk::uint32)(this->cleanColor.r*255),(edk::uint32)(this->cleanColor.g*255),(edk::uint32)(this->cleanColor.b*255),(edk::uint32)255));//1.6
        this->window.clear(sf::Color((edk::uint32)(this->cleanColor.r*255),
                                     (edk::uint32)(this->cleanColor.g*255),
                                     (edk::uint32)(this->cleanColor.b*255),
                                     (edk::uint32)255
                                     )
                           );//2.0
    }
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA5B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

edk::uint32 Window::getViewCount()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA5D begin
{
    //
    return this->viewWindow.getCount();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA5D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::addSubview(View *addView)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA5F begin
{
    //Add the view to the viewWindow
    return this->viewWindow.addSubview(addView);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

View* Window::getSubview(uint64 n)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA64 begin
{
    return this->viewWindow.getSubview(n);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint64 Window::getSubviewId(View *subView)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA69 begin
{
    return this->getSubviewId(subView);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA69 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::removeSubview(View *subView){
    //
    this->viewWindow.removeSubview(subView);
}

void Window::removeAllSubview(){
    this->viewWindow.removeAllSubview();
}

void Window::windowRender(bool show)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA6E begin
{
    //primeiro testa se possui uma window
    if(this->isOpened()){
        //seta o mouse
        //this->window.Show(show);//1.6
        this->window.setVisible(show);//2.0
    }
    this->renderWindow=show;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA6E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::showWindow()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA71 begin
{
    this->windowRender(true);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA71 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::hideWindow()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA73 begin
{
    this->windowRender(false);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA73 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::mouseRender(bool show)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA75 begin
{
    //primeiro testa se possui uma window
    if(this->isOpened()){
        //seta o mouse
        //this->window.ShowMouseCursor(show);//1.6
        this->window.setMouseCursorVisible(show);//2.0
    }
    this->renderMouse=show;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA75 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::showMouse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA78 begin
{
    //Seta para mostrar o mouse
    this->mouseRender(true);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA78 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::hideMouse()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA7A begin
{
    //Seta para esconder o mouse
    this->mouseRender(false);
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA7A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::setMousePosition(vec2i32 pos)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA7C begin
{
    //testa se a janela esta aberta
    if(this->isOpened()){
        //seta a posicao do mouse
        //this->window.SetCursorPosition(pos.x,pos.y);//1.6
        sf::Mouse::setPosition(sf::Vector2i(pos.x,pos.y), this->window);//2.0
        saveMousePos = pos;
        //retorna true
        return true;
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA7C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::setMousePosition(int32 x, int32 y)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA80 begin
{
    //seta o mouse
    return this->setMousePosition(edk::vec2i32(x,y));
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA80 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::setWindowPosition(vec2i32 pos)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA84 begin
{
    //testa se a janela esta aberta
    if(this->isOpened()){
        //seta a posicao do mouse
        //this->window.SetPosition(pos.x,pos.y);//1.6
        this->window.setPosition(sf::Vector2i(pos.x,pos.y));//2.0
        //retorna true
        return true;
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA84 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::setWindowPosition(int32 x, int32 y)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA87 begin
{
    //
    return this->setWindowPosition(edk::vec2i32(x,y));
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::setWindowSize(size2ui32 size)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA8B begin
{
    //testa se a janela esta aberta
    if(this->isOpened()){
        //save the size of the window
        this->windowSize = size;
        //seta a posicao do mouse
        //this->window.SetSize(size.width,size.height);//1.6
        this->window.setSize(sf::Vector2u(size.width,size.height));//2.0
        //seta o tamanho da view
        this->updateViewSize();
        //retorna true
        return true;
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::setWindowSize(uint32 width, uint32 height)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA8E begin
{
    //
    return this->setWindowSize(edk::size2ui32(width,height));
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA8E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

//Update the views
void Window::updateViews(){
    //test if have a mousePress ou Release
    if(this->eventMousePressed()){
        //test pressed with views
        this->viewWindow.contact(edk::vec2f32(this->getMousePos().x,this->getMousePos().y),edk::mouse::state::pressed,&this->events.mousePressed);
    }
    if(this->eventMouseMoved()){
        //
        this->viewWindow.contact(edk::vec2f32(this->getMousePos().x,this->getMousePos().y),edk::mouse::state::moved,&this->events.mouseMoving);
    }
    if(this->eventMouseRelease()){
        //test released with views
        this->viewWindow.contact(edk::vec2f32(this->getMousePos().x,this->getMousePos().y),edk::mouse::state::released,&this->events.mouseRelease);
    }

    //update the view
    this->updateView(&this->viewWindow);
}
//update the viewGU
void Window::updateView(edk::View* view){
    //test the viewGU
    if(view){
        //update the envents on the view
        view->update(&this->events);
        //update the animations on the view
        view->updateAnimations();
        //tets if is not a leaf
        if(!view->isLeaf()){
            //load the temp
            edk::ViewController* temp=(edk::ViewController*)view;
            //then search anothers views
            for(edk::uint64 i=0u;i<temp->getCount();i++){
                //load the nextView
                edk::ViewController* tempController = (edk::ViewController*)temp->getSubview(i);
                //test if have the nextView
                if(tempController){
                    //then test if is a ViewGU
                    this->updateView(tempController);
                }
            }
        }
    }
}
//contactView
void Window::mousePressView(edk::ViewController* view, edk::vec2i32 point, edk::vector::Stack<edk::uint32> buttons){
    //
    if(view && point.x){
        //remove the warning
    }
    //buttons cant delete
    buttons.cantDestroy();
}
void Window::mouseReleaseView(edk::ViewController* view, edk::vec2i32 point, edk::vector::Stack<edk::uint32> buttons){
    //
    if(view && point.x){
        //remove the warning
    }

    //buttons cant delete
    buttons.cantDestroy();
}

bool Window::drawStart()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA92 begin
{
    //Tetsa se finalizou o render antes e se a janela esta aberta
    if(!this->activeRender && this->isOpened()){
        //pode setar o render
        //this->window.SetActive(true);//1.6
        this->window.setActive(true);//2.0
        //seta activeRender como true
        this->activeRender=true;
        //retorna true
        return true;
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA92 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::drawEnd()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA94 begin
{
    //Tetsa se iniciou o render antes e se a janela esta aberta
    if(this->activeRender && this->isOpened()){
        //pode setar o render
        //this->window.SetActive(false);//1.6
        this->window.setActive(false);//2.0
        //seta activeRender como false
        this->activeRender=false;
        //retorna true
        return true;
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA94 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Window::drawView()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA96 begin
{
    //Start the draw
    this->drawStart();

    //load the identity matrix
    edk::GU::guLoadIdentity();

    //Set the clean color to the first view backGroundColor
    this->viewWindow.backgroundColor(this->cleanColor.r,
                                     this->cleanColor.g,
                                     this->cleanColor.b,
                                     1.f
                                     );

    //draw the view
    this->viewWindow.draw(
                this->viewWindow.frame
                );

    //End the drawing
    this->drawEnd();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA96 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::flip()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA9A begin
{
    //testa se possui uma janela e se ja desenhou
    if(this->isOpened() && !this->activeRender){
        //Pode renderizar na tela
        //this->window.Display();//1.6
        this->window.display();//2.0
        //retorna true
        return true;
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA9A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::render()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA9C begin
{
    //
    return this->flip();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA9C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

size2ui32 Window::getSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA9E begin
{
    //testa se a janela esta aberta
    edk::size2ui32 ret(0u,0u);
    if(this->isOpened()){
        //retorna o tamanho da window
        /*
        ret = edk::size2ui32((edk::uint32)this->window.GetDefaultView().GetRect().GetWidth(),
                     (edk::uint32)this->window.GetDefaultView().GetRect().GetHeight()
                     );
        */
        ret = this->windowSize;
    }
    //senao retorna um tamanho zerado
    return ret;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AA9E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

size2ui32 Window::getScreenSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA0 begin
{
    //testa se a janela esta aberta
    edk::size2ui32 ret(0u,0u);
    if(this->isOpened()){
        //retorna o tamanho da view
        //ret = edk::size2ui32(this->window.GetWidth(),this->window.GetHeight());//1.6
        ret = edk::size2ui32(this->window.getSize().x,this->window.getSize().y);//2.0
    }
    //senao retorna um tamanho zerado
    return ret;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint32 Window::getWidth()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA2 begin
{
    //
    if(this->isOpened()){
        //
        //return this->window.GetWidth();//1.6
        return this->window.getSize().x;//2.0
    }
    //senao retorna 0u
    return 0u;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint32 Window::getHeight()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA4 begin
{
    //
    if(this->isOpened()){
        //
        //return this->window.GetHeight();//1.6
        return this->window.getSize().y;//2.0
    }
    //senao retorna 0u
    return 0u;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

vec2i32 Window::getMousePos()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA6 begin
{
    //
    //senao retorna uma posicao zerada
    //return this->mousePos;
    return this->events.mousePos;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

vec2i32 Window::eventGetMouseMoved()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAA8 begin
{
    //
    //return this->mouseMove;
    return this->events.mouseMove;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAAB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventLostFocus()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAAD begin
{
    return this->events.lostFocus;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAAD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventGainedFocus()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAAF begin
{
    return this->events.gainedFocus;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAAF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventButtonClose()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB1 begin
{
    //
    bool temp = events.buttonExit;
    events.buttonExit=false;
    return temp;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventKeyPressed()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB3 begin
{
    //
    return (bool)this->eventGetKeyPressedSize();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventKeyRelease()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB5 begin
{
    //
    return (bool)this->eventGetKeyReleaseSize();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventKeyHolded(){
    return (bool)this->eventGetKeyHoldedSize();
}

uint32 Window::eventGetKeyPressedSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB7 begin
{
    //Retorna o tamanho do vector
    return this->events.keyPressed.size();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint32 Window::eventGetKeyReleaseSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB9 begin
{
    //Retorna o tamanho do vetor
    return this->events.keyRelease.size();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAB9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint32 Window::eventGetKeyHoldedSize(){
    return this->events.keyHolded.size();
}

uint32 Window::eventGetKeyPressed(uint32 pos)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AABB begin
{
    //
    if(pos<this->events.keyPressed.size()){
        //
        return this->events.keyPressed[pos];
    }
    //senao retorna 0u
    return 0u;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AABB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint32 Window::eventGetKeyRelease(uint32 pos)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AABE begin
{
    if(pos<this->events.keyRelease.size()){
        //
        return this->events.keyRelease[pos];
    }
    //senao retorna 0u
    return 0u;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AABE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint32 Window::eventGetKeyHolded(uint32 pos){

    if(pos<this->events.keyHolded.size()){
        //
        return this->events.keyHolded[pos];
    }
    //senao retorna 0u
    return 0u;
}

bool Window::eventMousePressed()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC1 begin
{
    //
    return (bool)this->eventGetMousePressedSize();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventMouseRelease()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC3 begin
{
    //
    return (bool)this->eventGetMouseReleaseSize();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventMouseHolded(){
    return (bool)this->eventGetMouseHoldedSize();
}

uint8 Window::eventGetMousePressedSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC5 begin
{
    //
    return this->events.mousePressed.size();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint8 Window::eventGetMouseReleaseSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC7 begin
{
    //
    return this->events.mouseRelease.size();
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint8 Window::eventGetMouseHoldedSize(){
    //
    return this->events.mouseHolded.size();
}

uint8 Window::eventGetMousePressed(uint32 pos)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC9 begin
{
    //
    if(pos<this->events.mousePressed.size()){
        //
        return this->events.mousePressed[pos];
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAC9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint8 Window::eventGetMouseRelease(uint32 pos)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AACC begin
{
    //
    if(pos<this->events.mouseRelease.size()){
        //
        return this->events.mouseRelease[pos];
    }
    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AACC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint8 Window::eventGetMouseHolded(uint32 pos){
    //
    if(pos<this->events.mouseHolded.size()){
        //
        return this->events.mouseHolded[pos];
    }
    //senao retorna false
    return false;
}

bool Window::eventMouseEnter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AACF begin
{
    //
    return this->events.mouseEnter;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AACF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventMouseExit()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD1 begin
{
    //
    return this->events.mouseExit;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventMouseMoved()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD3 begin
{
    //retorna se o mouse foi movido
    return this->events.mouseMoved;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int8 Window::getMouseScrollWheel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD5 begin
{
    //
    return (int8)this->events.mouseScrollWheel;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::eventResizeWindow()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD7 begin
{
    //retorna se redimencionou a janela
    return this->events.resize;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

size2i32 Window::getResize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD9 begin
{
    //
    return this->events.resizePos;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AAD9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Window::loadEvents()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AADB begin
{
    //Limpa os eventos
    this->cleanEvents();

    //Eventos da janela
    sf::Event event;
    //Input da janela
    //const sf::Input& input=window.GetInput();//1.6
    //2.0

    //while(window.GetEvent(event)){//1.6
    while(window.pollEvent(event)){//2.0
        //processa os eventos
        ///////////////////////////////////////////////////////////
        //JANELA FECHANDO
        //if(event.Type == sf::Event::Closed){//1.6
        if(event.type == sf::Event::Closed){//2.0
            //
            this->events.buttonExit=true;
        }
        //if(event.Type == sf::Event::LostFocus){//1.6
        if(event.type == sf::Event::LostFocus){//2.0
            //Minimize
            this->events.lostFocus=true;
            this->events.focus = false;
        }
        //if(event.Type == sf::Event::GainedFocus){//1.6
        if(event.type == sf::Event::GainedFocus){//2.0
            //unMinimize
            this->events.gainedFocus=true;
            this->events.focus=true;
        }
        ///////////////////////////////////////////////////////////

        ///////////////////////////////////////////////////////////
        //PRESSIONOU TECLA
        //if(event.Type == sf::Event::KeyPressed){//1.6
        if(event.type == sf::Event::KeyPressed){//2.0
            //carrega a tecla pressionada
            //this->events.keyPressed.pushBack(event.Key.Code);//1.6
            if(event.key.code>=0&&event.key.code<26){
                this->events.keyPressed.pushBack(event.key.code+'a') ;//2.0
            }
            else if(event.key.code>=26&&event.key.code<36){
                this->events.keyPressed.pushBack(event.key.code+ '0' - 26) ;//2.0
            }
            else{
                this->events.keyPressed.pushBack(event.key.code+256 - 36) ;//2.0
            }
        }
        //FIM PRESSIONOU TECLA
        ///////////////////////////////////////////////////////////

        ///////////////////////////////////////////////////////////
        //RETIROU DA PRESSAO A TECLA
        //if(event.Type == sf::Event::KeyReleased){//1.6
        if(event.type == sf::Event::KeyReleased){//2.0
            //carrega a tecla pressionada
            //this->events.keyRelease.pushBack(event.Key.Code);//1.6
            if(event.key.code>=0&&event.key.code<26){
                this->events.keyRelease.pushBack(event.key.code+'a') ;//2.0
            }
            else if(event.key.code>=26&&event.key.code<36){
                this->events.keyRelease.pushBack(event.key.code+ '0' - 26) ;//2.0
            }
            else{
                this->events.keyRelease.pushBack(event.key.code+256 - 36) ;//2.0
            }
        }
        //FIM RETIROU DA PRESSAO A TECLA
        ///////////////////////////////////////////////////////////


        ///////////////////////////////////////////////////////////
        //REDIMENCIONAMENTO DA JANELA
        //if(event.Type == sf::Event::Resized){//1.6
        if(event.type == sf::Event::Resized){//2.0
            /*
                sf::FloatRect NewSize(0, 0, event.Size.Width, event.Size.Height);
                window.GetDefaultView().SetFromRect(NewSize);
                */
            //resize true
            this->events.resize=true;
            //edk::size2ui32 tempView = edk::size2ui32(window.GetWidth(),window.GetHeight());//1.6
            edk::size2ui32 tempView = edk::size2ui32(window.getSize().x,window.getSize().y);//2.0
            //resizePos
            //this->resizePos = edk::size2i32(window.GetWidth(),window.GetHeight());
            /*
                this->resizePos = edk::size2i32(this->windowSize.width,this->windowSize.height) -
                                  edk::size2i32(tempView.width,tempView.height)
                                                ;
                */
            this->events.resizePos.width += (edk::int32)tempView.width - (edk::int32)this->windowSize.width;
            this->events.resizePos.height+= (edk::int32)tempView.height- (edk::int32)this->windowSize.height;

            //set the new size of the window
            this->windowSize = tempView;
            this->events.windowSize = this->windowSize;

            //Seta o tamanho da janela
            this->updateViewSize();
        }
        ///////////////////////////////////////////////////////////




        ///////////////////////////////////////////////////////////
        //MOUSE PRESSIONADO
        //if(event.Type == sf::Event::MouseButtonPressed){//1.6
        if(event.type == sf::Event::MouseButtonPressed){//2.0
            //
            //this->events.mousePressed.pushBack(event.MouseButton.Button+1u);//1.6
            this->events.mousePressed.pushBack(event.mouseButton.button+1u);//2.0

            this->mouseInside=true;
        }
        //FIM DO MOUSE PRESSIONADO
        ///////////////////////////////////////////////////////////




        ///////////////////////////////////////////////////////////
        //MOUSE ENTROU SAIU DA JANELA
        //if(event.Type == sf::Event::MouseEntered){//1.6
        if(event.type == sf::Event::MouseEntered){//2.0
            //
            this->events.mouseEnter=true;

            this->mouseInside=true;
        }
        //if(event.Type == sf::Event::MouseLeft){//1.6
        if(event.type == sf::Event::MouseLeft){//2.0
            //
            this->events.mouseExit=true;

            this->mouseInside=false;
        }
        //FIM DO MOUSE ENTROU SAIU DA JANELA
        ///////////////////////////////////////////////////////////





        ///////////////////////////////////////////////////////////
        //MOUSE SOLTO
        //if(event.Type == sf::Event::MouseButtonReleased){//1.6
        if(event.type == sf::Event::MouseButtonReleased){//2.0
            //
            //this->events.mouseRelease.pushBack(event.MouseButton.Button+1u);//1.6
            this->events.mouseRelease.pushBack(event.mouseButton.button+1u);//2.0
        }
        //FIM DO MOUSE SOLTO
        ///////////////////////////////////////////////////////////










        ///////////////////////////////////////////////////////////
        //MOUSE MOVIDO
        //if(event.Type == sf::Event::MouseMoved){//1.6
        if(event.type == sf::Event::MouseMoved){//2.0
            //
            this->events.mouseMoved=true;

            //Carrega a nova posicao do mouse
            edk::vec2ui32 mouseTemp = edk::vec2ui32((edk::uint32)sf::Mouse::getPosition(this->window).x,(edk::uint32)sf::Mouse::getPosition(this->window).y);//2.0
            //Calcula a distancia movida
            this->events.mouseMove = edk::vec2i32((edk::int32)mouseTemp.x-(edk::int32)this->saveMousePos.x,
                                                  (edk::int32)mouseTemp.y-(edk::int32)this->saveMousePos.y
                                                  );
            //salva a nova posicao do mouse
            this->events.mousePos = edk::vec2i32(mouseTemp.x,mouseTemp.y);
        }
        else{
            this->events.mouseMove = edk::vec2i32(0,0);
        }
        //FIM MOUSE MOVIDO
        ///////////////////////////////////////////////////////////







        ///////////////////////////////////////////////////////////
        //MOUSE SCROLL
        //if(event.Type == sf::Event::MouseWheelMoved){//1.6
        if(event.type == sf::Event::MouseWheelMoved){//2.0
            //
            /*
                printf("\nScrool %d"
                       ,event.MouseWheel.Delta
                       );
                */
            //this->events.mouseScrollWheel=event.MouseWheel.Delta;//1.6
            this->events.mouseScrollWheel=event.mouseWheel.delta;//2.0

            this->mouseInside=true;
        }
        //FIM MOUSE SCROLL
        ///////////////////////////////////////////////////////////



        //if(event.Type == sf::Event::JoyButtonPressed){//1.6
        if(event.type == sf::Event::JoystickButtonPressed){//2.0
            //
            /*
                printf("\nJoyButtonPressed joy == %u button == %u"
                       ,event.JoyButtonEvent.JoystickId
                       ,event.JoyButtonEvent.Button
                       );
                */
        }





    }
    //load mousePosition
    //events.mousePos = edk::vec2i32( input.GetMouseX(),input.GetMouseY());//1.6
    events.mousePos = edk::vec2i32( sf::Mouse::getPosition(this->window).x,sf::Mouse::getPosition(this->window).y);//2.0
    this->saveMousePos.x = this->events.mousePos.x;
    this->saveMousePos.y = this->events.mousePos.y;
    events.mousePosWorld = edk::vec2i32( sf::Mouse::getPosition().x,sf::Mouse::getPosition().y);//2.0

    //save focus
    this->windowFocus = this->events.focus;

    //test if have focus
    if(this->windowFocus){
        //load the holded keys
        for(edk::int32 i=sf::Keyboard::A;i<sf::Keyboard::KeyCount;i=i+1){
            if(sf::Keyboard::isKeyPressed((sf::Keyboard::Key)i)){
                if(i>=0&&i<26)
                    this->events.keyHolded.pushBack(i+'a') ;//2.0
                else if(i>=26&&i<36)
                    this->events.keyHolded.pushBack(i+ '0' - 26) ;//2.0
                else
                    this->events.keyHolded.pushBack(i+256 - 36) ;//2.0
            }
        }

        if(this->mouseInside){
            //load the holded mouse button
            for(edk::int32 i=sf::Mouse::Left ;i<sf::Mouse::ButtonCount;i=i+1){
                if(sf::Mouse::isButtonPressed((sf::Mouse::Button)i)){
                    this->events.mouseHolded.pushBack(i+1u);
                }
            }
        }
    }

    //Testa os controlers
    /*
        for(edk::uint32 i=0u;i<2u;i++){
            //Adiciona o novo controler
            edk::Window::ctrlPressed temp;
            this->controllerPressed.push_back(temp);
            for(edk::uint32 j=0u;j<=15u;j++){
                //adiciona os valores
                if(input.IsJoystickButtonDown(i, j)){
                    //
                    printf("\nBotao %u controle %u"
                           ,i
                           ,j
                           );
                    }
            }
        }
*/

    //senao retorna false
    return false;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AADB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

size2ui32 Window::getDesktopSize()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AADD begin
{
    //Carrega o modo do desktop
    //sf::VideoMode DesktopMode = sf::VideoMode::GetDesktopMode();//1.6
    sf::VideoMode DesktopMode = sf::VideoMode::getDesktopMode();//2.0
    //seta o retorno
    //edk::size2ui32 temp(DesktopMode.Width,DesktopMode.Height);//1.6
    edk::size2ui32 temp(DesktopMode.width,DesktopMode.height);//2.0
    //carrega o desktop mode
    return temp;
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AADD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

uint32 Window::getDesktopBitsPerPixel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AADF begin
{
    //Carrega o modo do desktop
    //sf::VideoMode DesktopMode = sf::VideoMode::GetDesktopMode();//1.6
    sf::VideoMode DesktopMode = sf::VideoMode::getDesktopMode();//2.0
    //retorna os bits
    //return DesktopMode.BitsPerPixel;//1.6
    return DesktopMode.bitsPerPixel;//2.0
}
// section 127-0-1-1-268c1826:13ad7e2c651:-8000:000000000000AADF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace edk */
